/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.i2p;

import com.google.common.graph.Graph;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.geometry.Point2D;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.scene.paint.Color;
import javafx.util.Duration;
import java.awt.*;
import java.security.Key;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicInteger;

//Game class
public class Slither extends Application {

    private static final int width_ = 20;
    private static final int height_ = 20;
    private static final int tileSize_ = 30;
    private int playerOneYPos_ = height_/2;
    private int playerTwoYPos_ = height_/2 ;
    private int playerOneXPos_ = width_/4 ;
    private int playerTwoXPos_ = width_ - width_/4;
    private int playerOneScore = 0;
    private int playerTwoScore = 0;
    private boolean gameStarted_ = false;
    //create snakes
    //private Snake P1 = new Snake(3, tileSize_, 1, new SnakeSegment(playerOneXPos_, playerOneYPos_), 0, 1,Color.RED);
    //private Snake P2 = new Snake(3, tileSize_, 1, new SnakeSegment(playerTwoXPos_, playerTwoYPos_), 0, 1,Color.BLUE);



    @Override
    public void start(Stage stage) {
        Snake P1 = new Snake(5, new SnakeSegment(playerOneXPos_, playerOneYPos_), 0, -1, tileSize_, Color.RED);
        Snake P2 = new Snake(5, new SnakeSegment(playerTwoXPos_, playerTwoYPos_), 0, -1, tileSize_, Color.BLUE);
        stage.setTitle("Slither");
        //the snakes will be drawn on graphics context of the canvas
        Canvas can = new Canvas(width_ * tileSize_, height_ * tileSize_);
        Duration cycleDur = Duration.millis(500);
        AtomicInteger executionCount = new AtomicInteger(0);
        KeyFrame keyframe = new KeyFrame(cycleDur, event -> {
            run(can, P1, P2);
            int count = executionCount.incrementAndGet();
            if (count % 5 == 0) {
                System.out.println(count);
                P1.elongate();
                P2.elongate();
            }
        });
        Timeline timeLine = new Timeline();
        timeLine.getKeyFrames().add(keyframe);
        timeLine.setCycleCount(Timeline.INDEFINITE);


        can.setFocusTraversable(true);
        can.setOnKeyPressed(event -> {gameStarted_ = true;});

        // create background tiles
        GridPane grid = new GridPane();
        for (int i = 0; i < width_; i++){
            for (int j = 0; j < height_; j++){
                Pane pane = new Pane();
                pane.setPrefSize(tileSize_, tileSize_);
                if ((i+j) % 2 == 0){
                    pane.setStyle("-fx-background-color: lightgreen;");
                }
                else{
                    pane.setStyle("-fx-background-color: darkgreen;");
                }
                grid.add(pane, i, j);
            }
        }

        StackPane stackPane = new StackPane();
        stackPane.getChildren().add(grid);
        stackPane.getChildren().add(can);
        stage.setScene(new Scene(stackPane));
        stage.setResizable(false);
        stage.show();
        timeLine.play();

    }

    //runs the game
    private void run(Canvas can, Snake P1, Snake P2){
        GraphicsContext gc = can.getGraphicsContext2D();

        gc.clearRect(0, 0, width_ * tileSize_, height_ * tileSize_);

        if(gameStarted_) {

            if (P1.isAlive_() && P2.isAlive_()){
                can.setOnKeyPressed(event -> {
                    switch(event.getCode()){

                        case UP:
                            P2.updateDirection(0, -1);
                            break;
                        case DOWN:
                            P2.updateDirection(0, 1);
                            break;
                        case LEFT:
                            P2.updateDirection(-1, 0);
                            break;
                        case RIGHT:
                            P2.updateDirection(1, 0);
                            break;
                        case W:
                            P1.updateDirection(0, -1);
                            break;
                        case S:
                            P1.updateDirection(0, 1);
                            break;
                        case A:
                            P1.updateDirection(-1, 0);
                            break;
                        case D:
                            P1.updateDirection(1, 0);
                            break;

                    }
                });

                if (P1.outOfBounds(width_, height_) || P2.outOfBounds(width_, height_)){
                    System.out.println("out of bounds");
                }

                if (P1.collision(P2)){
                    System.out.println("collision");
                }

                if (P2.collision(P1)){
                    System.out.println("collision");
                }

                P1.move();
                P1.draw(gc);
                P2.move();
                P2.draw(gc);
            }
            else if (!P1.isAlive_()){
                //todo display "P2 won!" in middle and reset game on click
                System.out.println("P2 won!");
            }
            else if (!P2.isAlive_()){
                System.out.println("P1 won!");
            }
            else{
                System.out.println("Draw!");
            }
        }
        else {
            P1.draw(gc);
            P2.draw(gc);
        }
    }


    public static void main(String[] args) {
        launch();
    }


}